apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iua2Frb3Iub3ZoIjp7InVzZXJuYW1lIjoiZ2l0IiwicGFzc3dvcmQiOiJCNHRlYXUxMjMiLCJlbWFpbCI6ImdpdEB0ZXN0LmNvbSIsImF1dGgiOiJaMmwwT2tJMGRHVmhkVEV5TXc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: docker
type: kubernetes.io/dockerconfigjson
